# url: http://gist-mail.herokuapp.com
# repository: https://github.com/sanemat/gist-mail
# ref: 7000982634dd360469ab8bbfc1190d65f90f5ddb
# memo:
#   - railshackathon
language: ruby
rvm: 1.9.3
bundler_args: --deployment --without development production
before_install: gem update bundler
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load --quiet
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    - notification@example.com
script: bundle exec rspec -fd
