# url: http://qa.atmarkit.co.jp
# repository: omitted
# ref: omitted
# memo:
#   - http://qa.atmarkit.co.jp/q/2345
language: ruby
rvm: 1.9.3
bundler_args: --without development:production
before_install: gem update bundler
before_script:
  - RAILS_ENV=test rake db:create db:test:load --quiet
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
