# url: http://www.ohmyglasses.jp
# repository: omitted
# ref: omitted
# memo:
#   - rails
#   - spree
#   - https://gist.github.com/4080033
language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/settings.yml.example config/settings.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
bundler_args: --deployment --without development production
notifications:
  email:
    - notify@example.com
script: bundle exec rspec -fd
